service: todo-application-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

functions:
  todos:
    handler: tasks.handler
    environment: 
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}      
    events:         
      - http:
          method: get
          path: todos          
          cors: true

      - http:
          method: post
          path: todos         
          cors: true

      - http:
          method: put
          path: todos/{id}          
          cors: true

      - http:
          method: delete
          path: todos/{id}
          cors: true